services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/proddb
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tinhha
      POSTGRES_PASSWORD: tinhhapwd
      POSTGRES_DB: dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: